# Site settings
title: Nawras M. Amin | Personal Website
description: Personal Website of Nawras M. Amin
baseurl: 'https://strixsc.github.io/CV' # the subpath of your site, e.g. /blog
url: 'thestrix.ca' # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nawras M. Amin
user-description: Software Engineering Student at the university of Polytechnique Montreal looking for an internship in the field of information security or machine learning. Always striving to learn new technologies and adventure myself deeper into the world of knowledge. I have studied both the Comptia Security+ and the Network+ certifications and am currently working towards getting my CISSP certification aswell.  I have experience with numerous CTFs which have helped me understand a lot about common vulnerabilities, with my speciality being Web Challenges. Finally, through personal projects I have managed to learn a lot about the vaste world of artificial intelligence, about the numerous technologies that are available nowadays for web-development for both front-end and back-end and finally develop my problem-solving skills. 
user_title: Software Engineering Student
email: nawrasmamin@gmail.com
twitter_username: S7RIX
github_username:  StrixSC

exclude: ['package.json', 'src' , 'node_modules']
